<?php

namespace Database\Seeders;

use App\Models\Apartment;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

// Helpers
use Illuminate\Support\Str;


class ApartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $apartments = [
            // admin
            [
                "user_id"=> "1",
                "title"=> "Appartamento Milano - Loreto",
                "description"=> "Un appartamento completamente nuovo a Tua disposizione nel centro di Milano per un soggiorno di lavoro o per una vacanza. ",
                "main_img"=> "https://images.pexels.com/photos/709767/pexels-photo-709767.png?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "2",
                "max_rooms"=> "1",
                "max_beds"=> "2",
                "max_baths"=> "1",
                "mq"=> "39",
                "address"=> "via Padova, 1",
                "latitude"=> "45.490333960307254",
                "longitude"=> "9.222640613799705",
                "price"=> "88",
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Casa Lario - Isola Distric",
                "description"=> "Appartamento di circa 50 mq situato al secondo piano con ascensore. L'appartamento si compone di un ingresso, un soggiorno/cucina, una zona notte, un bagno finestrato e due balconcini. L’appartamento è interamente esposto sul cortile interno piantumato e per questo è particolarmente silenzioso.",
                "main_img"=> "https://images.pexels.com/photos/12401710/pexels-photo-12401710.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "3",
                "max_rooms"=> "2",
                "max_beds"=> "3",
                "max_baths"=> "1",
                "mq"=> "47",
                "address"=> "via Lario, 35",
                "latitude"=> "45.4922243689266",
                "longitude"=> "9.190210385517647",
                "price"=> "90",
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Maisonette a Porta Genova",
                "description"=> "Vicinissimo alla movida dei Navigli ma in posizione tranquilla. Appartamento in tipica casa di ringhiera a pochi passi dalla metro di Porta Genova. I bar e la vita dei locali di Ripa di Porta Ticinese e Alzaia Naviglio Grande a 5 minuti a piedi.",
                "main_img"=> "https://images.pexels.com/photos/5084182/pexels-photo-5084182.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "3",
                "max_rooms"=> "2",
                "max_beds"=> "3",
                "max_baths"=> "1",
                "mq"=> "65",
                "address"=> "Porta Genova, 1",
                "latitude"=> "45.45278177463842",
                "longitude"=> "9.167743975881145",
                "price"=> "90",
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Milano Centro Storico",
                "description"=> "Appartamento nel cuore di Milano, in un palazzo signorile, a pochi passi dal Duomo. Si trova al secondo piano, servito da ascensore; è presente un piccolo balcone che si affaccia sul cortile con un tavolino. Grande living con divano letto e TV; cucina open space completamente attrezzata, due camere da letto di cui una matrimoniale e una con letto una piazza e mezza. Bagno completo con doccia e vasca da bagno.",
                "main_img"=> "https://images.pexels.com/photos/709767/pexels-photo-709767.png?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "4",
                "max_rooms"=> "3",
                "max_beds"=> "4",
                "max_baths"=> "2",
                "mq"=> "90",
                "address"=> "via Torino, 12",
                "latitude"=> "45.462994",
                "longitude"=> "9.187311",
                "price"=> "156",
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Attrattivo monolocale",
                "description"=> "Monolocale ubicato in Porta Romana, quartiere storico di Milano con molteplici servizi a disposizione e un piacevole contesto architettonico da ammirare che renderà indimenticabile il vostro soggiorno in questa splendida città: uscendo dal cortile del palazzo il vostro sguardo incrocerà l'imponente sagoma della torre Velasca che vi accompagnerà nella vostra passeggiata per raggiungere comodamente Piazza Duomo (15 min).",
                "main_img"=> "https://images.pexels.com/photos/13722887/pexels-photo-13722887.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "2",
                "max_rooms"=> "1",
                "max_beds"=> "1",
                "max_baths"=> "1",
                "mq"=> "39",
                "address"=> "Corso di Porta Romana, 36",
                "latitude"=> "45.45638509818764",
                "longitude"=> "9.19529605501416",
                "price"=> "76",
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Milano Via Marghera",
                "description"=> "Questo meraviglioso appartamento/monolocale è stato completamente ristrutturato e pensato per offrire ai suoi ospiti il massimo della serenità. Studiato per persone che amano vivere nel centro città in una delle zone più vivaci e affascinati di Milano. La zona Marghera offre numerosi ristoranti e locali dove trascorrere giornate e serate in allegria. L'appartamento è progettato per due persone ed è fornito con tutto l'occorrente per un piacevole soggiorno.",
                "main_img"=> "https://media.istockphoto.com/id/1326191354/it/foto/divano-verde-negli-interni-moderni-dellappartamento-con-parete-vuota-e-tavolo-in-legno.jpg?b=1&s=612x612&w=0&k=20&c=2aC_iig57hDLbMOsmRK6pfPs1kLOu3YIgq8PvH9M5cI=",
                "max_guests"=> "2",
                "max_rooms"=> "1",
                "max_beds"=> "2",
                "max_baths"=> "1",
                "mq"=> "42",
                "address"=> "via Ravizza, 23",
                "latitude"=> "45.46950659468241",
                "longitude"=> "9.150075690169244",
                "price"=> "54",
                "visible"=> "1",
            ],
             // rob
             [
                "user_id"=> "2",
                "title"=> "Loft Martesana",
                "description"=> "Intimo Loft , nuovo e mai abitato con piccolo spazio esterno a pochi passi dal naviglio Martesana e dalla metro rossa",
                "main_img"=> "https://media.istockphoto.com/id/1272124325/it/foto/zona-giorno-in-stile-moderno-contemporaneo-interior-design-con-cornice-finestra-in-legno-e.jpg?b=1&s=612x612&w=0&k=20&c=PM__kLXlYOiWkp0MW3YvFDAQlhRIVN6rK_5x91Q8wA8=",
                "max_guests"=> "4",
                "max_rooms"=> "3",
                "max_beds"=> "4",
                "max_baths"=> "2",
                "mq"=> "120",
                "address"=> "via Jean Jaures, 22",
                "latitude"=> "45.50211153862963",
                "longitude"=> "9.217782976138452",
                "price"=> "130",
                "visible"=> "1",
            ],
            [
                "user_id"=> "2",
                "title"=> "Lambrate Design District",
                "description"=> "Incredibile e moderno appartamento nel quartiere di Lambrate, nel cuore del Fuorisalone.",
                "main_img"=> "https://images.pexels.com/photos/12401710/pexels-photo-12401710.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "3",
                "max_rooms"=> "2",
                "max_beds"=> "3",
                "max_baths"=> "1",
                "mq"=> "55",
                "address"=> "via Amadeo, 78",
                "latitude"=> "45.47233115069784",
                "longitude"=> "9.23995321393918",
                "price"=> "60",
                "visible"=> "1",
            ],
            // fra
            [
                "user_id"=> "3",
                "title"=> "Appartamento Sarpi",
                "description"=> "Grazie alla posizione centrale di questo alloggio, l'intero gruppo potrà accedere facilmente a tutte le attrazioni locali.",
                "main_img"=> "https://images.pexels.com/photos/5556176/pexels-photo-5556176.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "2",
                "max_rooms"=> "2",
                "max_beds"=> "2",
                "max_baths"=> "1",
                "mq"=> "57",
                "address"=> "via Paolo Sarpi, 33",
                "latitude"=> "45.48188240833758",
                "longitude"=> "9.175942223184103",
                "price"=> "110",
                "visible"=> "1",
            ],
            [
                "user_id"=> "3",
                "title"=> "Appartamento Garibaldi",
                "description"=> "Appartamento di 80mq, arredato in stile moderno zona garibaldi . Fermata metro (monumentale). L’appartamento si trova al secondo piano dotato di ascensore. All’interno troverete una cucina accessoriata, un divano,un tavolo e una Smart tv. Nella camera ci sarà un letto matrimoniale ed una cabina armadio. I bagni sono dotati di un’ampia doccia e due lavandini.",
                "main_img"=> "https://images.pexels.com/photos/12401710/pexels-photo-12401710.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "4",
                "max_rooms"=> "3",
                "max_beds"=> "4",
                "max_baths"=> "2",
                "mq"=> "80",
                "address"=> "corso Garibaldi, 44",
                "latitude"=> "45.477030527183636",
                "longitude"=> "9.183889652097049",
                "price"=> "130",
                "visible"=> "1",
            ],
            // andre
            [
                "user_id"=> "4",
                "title"=> "Monolocale Porta Venezia",
                "description"=> "L'appartamento è moderno e arredato in stile minimal e orientale, in zona porta Venezia che è un' area multietnica e queer, adatta per chi vuole uscire dalla monotonia.",
                "main_img"=> "https://images.pexels.com/photos/11784605/pexels-photo-11784605.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "2",
                "max_rooms"=> "1",
                "max_beds"=> "2",
                "max_baths"=> "1",
                "mq"=> "35",
                "address"=> "via Melzo, 33",
                "latitude"=> "45.47360516288336",
                "longitude"=> "9.209218142606147",
                "price"=> "67",
                "visible"=> "1",
            ],
            [
                "user_id"=> "4",
                "title"=> "Casa in Città Studi",
                "description"=> "Appartamento in zona centrale vicino alla linee 1 e 2 della metro. E' dotato di televisione, connessione internet illimitata e superveloce, armadio, lavatrice, stendipanni e ferro da stiro. La cucina è completa di tutto con un ampio tavolo.",
                "main_img"=> "https://images.pexels.com/photos/12401710/pexels-photo-12401710.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "4",
                "max_rooms"=> "4",
                "max_beds"=> "4",
                "max_baths"=> "2",
                "mq"=> "95",
                "address"=> "viale Bazzini, 2",
                "latitude"=> "45.48337825558275",
                "longitude"=> "9.225330504980949",
                "price"=> "90",
                "visible"=> "1",
            ],
             // samu
             [
                "user_id"=> "5",
                "title"=> "Centro Storico",
                "description"=> "A soli dieci minuti a piedi dal Duomo di Milano, l'appartamento si trova nel cuore della città in uno dei quartieri più caratteristici e autentici del centro. In pochi passi si raggiunge la Torre Velasca, la chiesa di Santa Maria delle Grazie, la Basilica di Sant'Ambrogio e la fermata delle metropolitana Missori.",
                "main_img"=> "https://images.pexels.com/photos/8171119/pexels-photo-8171119.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "2",
                "max_rooms"=> "2",
                "max_beds"=> "1",
                "max_baths"=> "1",
                "mq"=> "50",
                "address"=> "corso Italia, 24",
                "latitude"=> "45.457486096717545",
                "longitude"=> "9.187393107585576",
                "price"=> "124",
                "visible"=> "1",
            ],
            [
                "user_id"=> "5",
                "title"=> "Green Suite",
                "description"=> "Appartamento in caratteristica casa di ringhiera, affacciato su un cortile interno fiorito e silenzioso: sentirete solo gli uccellini cantare la mattina! L'ingresso è su balcone privato, al primo piano, senza passaggio. Recentemente ristrutturato, accogliente, dotato di aria condizionata, cucina attrezzata, bagno con doccia ampia e piccola lavanderia separata.",
                "main_img"=> "https://images.pexels.com/photos/212185/pexels-photo-212185.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "3",
                "max_rooms"=> "3",
                "max_beds"=> "3",
                "max_baths"=> "1",
                "mq"=> "70",
                "address"=> "via Fusetti, 2",
                "latitude"=> "45.451139909289665",
                "longitude"=> "9.174236438915148",
                "price"=> "65",
                "visible"=> "1",
            ],
            // manu
            [
                "user_id"=> "6",
                "title"=> "Appartamento CityLife",
                "description"=> "Un appartamento appena ristrutturato in un palazzo signorile della zona più comoda, servita e sicura di tutta la città (collegata con metro lilla e tram).",
                "main_img"=> "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "4",
                "max_rooms"=> "4",
                "max_beds"=> "4",
                "max_baths"=> "2",
                "mq"=> "50",
                "address"=> "viale Ezio, 4",
                "latitude"=> "45.473593258842726",
                "longitude"=> "9.15450252542119",
                "price"=> "90",
                "visible"=> "1",
            ],
            [
                "user_id"=> "6",
                "title"=> "Appartamento via Tortona",
                "description"=> "Uno studio, appena ristrutturato, comodo per due persone, nella alberata via Solari, zona della moda e del design di Milano. Tutti servizi a portata di due passi. Ben servito dai mezzi pubblici di superficie e metro.",
                "main_img"=> "https://images.pexels.com/photos/763148/pexels-photo-763148.jpeg?auto=compress&cs=tinysrgb&w=800",
                "max_guests"=> "2",
                "max_rooms"=> "3",
                "max_beds"=> "2",
                "max_baths"=> "1",
                "mq"=> "65",
                "address"=> "via Tortona, 12",
                "latitude"=> "45.451444670735484",
                "longitude"=> "9.16062359986951",
                "price"=> "70",
                "visible"=> "1",
            ],
        ];

        foreach ($apartments as $key => $apartment) {
            Apartment::create([
                'user_id' => $apartment['user_id'],
                'title' => $apartment['title'],
                'slug' => Str::slug($apartment['title']),
                'description' => $apartment['description'],
                'main_img' => $apartment['main_img'],
                'max_guests' => $apartment['max_guests'],
                'max_rooms' => $apartment['max_rooms'],
                'max_beds' => $apartment['max_beds'],
                'max_baths' => $apartment['max_baths'],
                'mq' => $apartment['mq'],
                'address' => $apartment['address'],
                'latitude' => $apartment['latitude'],
                'longitude' => $apartment['longitude'],
                'price' => $apartment['price'],
                'visible' => $apartment['visible'],

             ]);
        }

    }
}
