<?php

namespace Database\Seeders;

use App\Models\Apartment;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

// Helpers
use Illuminate\Support\Str;


class ApartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $apartments = [
            // admin
            [
                "user_id"=> "1",
                "title"=> "Appartamento Milano - Loreto",
                "description"=> "Un appartamento completamente nuovo a Tua disposizione nel centro di Milano per un soggiorno di lavoro o per una vacanza. ",
                "main_img"=> "apartments/01.jpg",
                "max_guests"=> "2",
                "rooms"=> "1",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "39",
                "address"=> "via Padova, 1",
                "latitude"=> "45.48703",
                "longitude"=> "9.21771",
                "price"=> 88.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Casa Lario - Isola District",
                "description"=> "Appartamento di circa 50 mq situato al secondo piano con ascensore. L'appartamento si compone di un ingresso, un soggiorno/cucina, una zona notte, un bagno finestrato e due balconcini. L’appartamento è interamente esposto sul cortile interno piantumato e per questo è particolarmente silenzioso.",
                "main_img"=> "apartments/02.jpg",
                "max_guests"=> "3",
                "rooms"=> "2",
                "beds"=> "3",
                "baths"=> "1",
                "mq"=> "47",
                "address"=> "via Lario, 31",
                "latitude"=> "45.39832",
                "longitude"=> "9.2462",
                "price"=> 90.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Maisonette a Porta Genova",
                "description"=> "Vicinissimo alla movida dei Navigli ma in posizione tranquilla. Appartamento in tipica casa di ringhiera a pochi passi dalla metro di Porta Genova. I bar e la vita dei locali di Ripa di Porta Ticinese e Alzaia Naviglio Grande a 5 minuti a piedi.",
                "main_img"=> "apartments/03.jpg",
                "max_guests"=> "3",
                "rooms"=> "2",
                "beds"=> "3",
                "baths"=> "1",
                "mq"=> "65",
                "address"=> "Porta Genova, 1",
                "latitude"=> "45.45062",
                "longitude"=> "9.16785",
                "price"=> 90.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Milano Centro Storico",
                "description"=> "Appartamento nel cuore di Milano, in un palazzo signorile, a pochi passi dal Duomo. Si trova al secondo piano, servito da ascensore; è presente un piccolo balcone che si affaccia sul cortile con un tavolino. Grande living con divano letto e TV; cucina open space completamente attrezzata, due camere da letto di cui una matrimoniale e una con letto una piazza e mezza. Bagno completo con doccia e vasca da bagno.",
                "main_img"=> "apartments/04.jpg",
                "max_guests"=> "4",
                "rooms"=> "3",
                "beds"=> "4",
                "baths"=> "2",
                "mq"=> "90",
                "address"=> "via Torino, 13",
                "latitude"=> "45.46321",
                "longitude"=> "9.18772",
                "price"=> 156.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Attrattivo monolocale",
                "description"=> "Monolocale ubicato in Porta Romana, quartiere storico di Milano con molteplici servizi a disposizione e un piacevole contesto architettonico da ammirare che renderà indimenticabile il vostro soggiorno in questa splendida città: uscendo dal cortile del palazzo il vostro sguardo incrocerà l'imponente sagoma della torre Velasca che vi accompagnerà nella vostra passeggiata per raggiungere comodamente Piazza Duomo (15 min).",
                "main_img"=> "apartments/05.jpg",
                "max_guests"=> "2",
                "rooms"=> "1",
                "beds"=> "1",
                "baths"=> "1",
                "mq"=> "39",
                "address"=> "Corso di Porta Romana, 36",
                "latitude"=> "45.4588",
                "longitude"=> "9.19132",
                "price"=> 76.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Milano Via Marghera",
                "description"=> "Questo meraviglioso appartamento/monolocale è stato completamente ristrutturato e pensato per offrire ai suoi ospiti il massimo della serenità. Studiato per persone che amano vivere nel centro città in una delle zone più vivaci e affascinati di Milano. La zona Marghera offre numerosi ristoranti e locali dove trascorrere giornate e serate in allegria. L'appartamento è progettato per due persone ed è fornito con tutto l'occorrente per un piacevole soggiorno.",
                "main_img"=> "apartments/06.jpg",
                "max_guests"=> "2",
                "rooms"=> "1",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "42",
                "address"=> "via Ravizza, 23",
                "latitude"=> "45.46787",
                "longitude"=> "9.1522",
                "price"=> 54.00,
                "visible"=> "1",
            ],
             // rob
             [
                "user_id"=> "2",
                "title"=> "Loft Martesana",
                "description"=> "Intimo Loft , nuovo e mai abitato con piccolo spazio esterno a pochi passi dal naviglio Martesana e dalla metro rossa",
                "main_img"=> "apartments/07.jpg",
                "max_guests"=> "4",
                "rooms"=> "3",
                "beds"=> "4",
                "baths"=> "2",
                "mq"=> "120",
                "address"=> "via Jean Jaures, 8",
                "latitude"=> "45.50159",
                "longitude"=> "9.21945",
                "price"=> 130.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "2",
                "title"=> "Lambrate Design District",
                "description"=> "Incredibile e moderno appartamento nel quartiere di Lambrate, nel cuore del Fuorisalone.",
                "main_img"=> "apartments/08.jpg",
                "max_guests"=> "3",
                "rooms"=> "2",
                "beds"=> "3",
                "baths"=> "1",
                "mq"=> "55",
                "address"=> "via Amadeo, 78",
                "latitude"=> "45.47092",
                "longitude"=> "9.23338",
                "price"=> 60.00,
                "visible"=> "1",
            ],
            // fra
            [
                "user_id"=> "3",
                "title"=> "Appartamento Sarpi",
                "description"=> "Grazie alla posizione centrale di questo alloggio, l'intero gruppo potrà accedere facilmente a tutte le attrazioni locali.",
                "main_img"=> "apartments/09.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "57",
                "address"=> "via Paolo Sarpi, 10",
                "latitude"=> "45.48137",
                "longitude"=> "9.17588",
                "price"=> 110.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "3",
                "title"=> "Appartamento Garibaldi",
                "description"=> "Appartamento di 80mq, arredato in stile moderno zona garibaldi . Fermata metro (monumentale). L’appartamento si trova al secondo piano dotato di ascensore. All’interno troverete una cucina accessoriata, un divano,un tavolo e una Smart tv. Nella camera ci sarà un letto matrimoniale ed una cabina armadio. I bagni sono dotati di un’ampia doccia e due lavandini.",
                "main_img"=> "apartments/10.jpg",
                "max_guests"=> "4",
                "rooms"=> "3",
                "beds"=> "4",
                "baths"=> "2",
                "mq"=> "80",
                "address"=> "corso Garibaldi, 44",
                "latitude"=> "45.47492",
                "longitude"=> "9.18365",
                "price"=> 130.00,
                "visible"=> "1",
            ],
            // andre
            [
                "user_id"=> "4",
                "title"=> "Monolocale Porta Venezia",
                "description"=> "L'appartamento è moderno e arredato in stile minimal e orientale, in zona porta Venezia che è un' area multietnica e queer, adatta per chi vuole uscire dalla monotonia.",
                "main_img"=> "apartments/11.jpg",
                "max_guests"=> "2",
                "rooms"=> "1",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "35",
                "address"=> "via Melzo, 33",
                "latitude"=> "45.47454",
                "longitude"=> "9.2086",
                "price"=> 67.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "4",
                "title"=> "Casa in Città Studi",
                "description"=> "Appartamento in zona centrale vicino alla linee 1 e 2 della metro. E' dotato di televisione, connessione internet illimitata e superveloce, armadio, lavatrice, stendipanni e ferro da stiro. La cucina è completa di tutto con un ampio tavolo.",
                "main_img"=> "apartments/12.jpg",
                "max_guests"=> "4",
                "rooms"=> "4",
                "beds"=> "4",
                "baths"=> "2",
                "mq"=> "95",
                "address"=> "via Nicola Porpora, 63",
                "latitude"=> "45.4812",
                "longitude"=> "9.22511",
                "price"=> 90.00,
                "visible"=> "1",
            ],
             // samu
             [
                "user_id"=> "5",
                "title"=> "Centro Storico",
                "description"=> "A soli dieci minuti a piedi dal Duomo di Milano, l'appartamento si trova nel cuore della città in uno dei quartieri più caratteristici e autentici del centro. In pochi passi si raggiunge la Torre Velasca, la chiesa di Santa Maria delle Grazie, la Basilica di Sant'Ambrogio e la fermata delle metropolitana Missori.",
                "main_img"=> "apartments/13.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "1",
                "baths"=> "1",
                "mq"=> "50",
                "address"=> "corso Italia, 24",
                "latitude"=> "45.45636",
                "longitude"=> "9.18745",
                "price"=> 124.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "5",
                "title"=> "Green Suite",
                "description"=> "Appartamento in caratteristica casa di ringhiera, affacciato su un cortile interno fiorito e silenzioso: sentirete solo gli uccellini cantare la mattina! L'ingresso è su balcone privato, al primo piano, senza passaggio. Recentemente ristrutturato, accogliente, dotato di aria condizionata, cucina attrezzata, bagno con doccia ampia e piccola lavanderia separata.",
                "main_img"=> "apartments/14.jpg",
                "max_guests"=> "3",
                "rooms"=> "3",
                "beds"=> "3",
                "baths"=> "1",
                "mq"=> "70",
                "address"=> "via Fusetti, 2",
                "latitude"=> "45.45071",
                "longitude"=> "9.17477",
                "price"=> 65.00,
                "visible"=> "1",
            ],
            // manu
            [
                "user_id"=> "6",
                "title"=> "Appartamento CityLife",
                "description"=> "Un appartamento appena ristrutturato in un palazzo signorile della zona più comoda, servita e sicura di tutta la città (collegata con metro lilla e tram).",
                "main_img"=> "apartments/15.jpg",
                "max_guests"=> "4",
                "rooms"=> "4",
                "beds"=> "4",
                "baths"=> "2",
                "mq"=> "50",
                "address"=> "viale Ezio, 4",
                "latitude"=> "45.47381",
                "longitude"=> "9.15277",
                "price"=> 90.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "6",
                "title"=> "Appartamento via Tortona",
                "description"=> "Uno studio, appena ristrutturato, comodo per due persone, nella alberata via Solari, zona della moda e del design di Milano. Tutti servizi a portata di due passi. Ben servito dai mezzi pubblici di superficie e metro.",
                "main_img"=> "apartments/16.jpg",
                "max_guests"=> "2",
                "rooms"=> "3",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "65",
                "address"=> "via Tortona, 12",
                "latitude"=> "45.4538",
                "longitude"=> "9.16857",
                "price"=> 70.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Appartamento Lambrate",
                "description"=> "Appartamento appena rinnovato e riarredato in una tranquilla zona di Lambrate.",
                "main_img"=> "apartments/17.jpg",
                "max_guests"=> "3",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "44",
                "address"=> "via Gaspare Aselli, 21",
                "latitude"=> "45.47038",
                "longitude"=> "9.23005",
                "price"=> 70.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "2",
                "title"=> "Mini casa moderna",
                "description"=> "Questa bellissima casina è perfetta per soggiornare in vicino al centro a Milano.",
                "main_img"=> "apartments/18.jpg",
                "max_guests"=> "2",
                "rooms"=> "1",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "38",
                "address"=> "via Ernesto Teodoro Moneta, 2",
                "latitude"=> "45.32257",
                "longitude"=> "9.13973",
                "price"=> 54.00,
                "visible"=> "0",
            ],
            [
                "user_id"=> "3",
                "title"=> "Milky House Milan",
                "description"=> "La Milky House Milan è una ex latteria storica trasformata in un piccolo loft pensato da un viaggiatore per altri viaggiatori.",
                "main_img"=> "apartments/19.jpg",
                "max_guests"=> "3",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "54",
                "address"=> "piazzale Luigi Emanuele Corvetto, 5",
                "latitude"=> "45.4394",
                "longitude"=> "9.2247",
                "price"=> 43.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "4",
                "title"=> "Ca' Granda",
                "description"=> "Questo spazio accogliente e confortevole è ideale per viaggiatori singoli, coppie o piccole famiglie che cercano una posizione comoda e un'atmosfera accogliente.",
                "main_img"=> "apartments/20.jpg",
                "max_guests"=> "5",
                "rooms"=> "3",
                "beds"=> "3",
                "baths"=> "2",
                "mq"=> "87",
                "address"=> "viale Ca' Granda, 21",
                "latitude"=> "45.50766",
                "longitude"=> "9.19521",
                "price"=> 78.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "5",
                "title"=> "Bilocale via Botta",
                "description"=> "Grazioso bilocale su due piani. Zona notte con accesso scala a chiocciola, con letto alla francese, divanoletto singolo, gran armadio e scrivania. ",
                "main_img"=> "apartments/21.jpg",
                "max_guests"=> "4",
                "rooms"=> "2",
                "beds"=> "4",
                "baths"=> "1",
                "mq"=> "76",
                "address"=> "via Carlo Botta, 13",
                "latitude"=> "45.45376",
                "longitude"=> "9.2048",
                "price"=> 45.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "6",
                "title"=> "Appartamento cozy",
                "description"=> "Appartamento attrezzato a nord di Milano. La nostra Cozy Double Room dispone di un letto matrimoniale, armadio e scrivania per zona lavoro e/o TV.",
                "main_img"=> "apartments/22.jpg",
                "max_guests"=> "3",
                "rooms"=> "2",
                "beds"=> "3",
                "baths"=> "1",
                "mq"=> "50",
                "address"=> "piazza Firenze, 43",
                "latitude"=> "45.48785",
                "longitude"=> "9.15634",
                "price"=> 43.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Appartamento grande via Farini",
                "description"=> "Grazioso alloggio posto in uno dei più bei quartieri Milanesi: lo splendido Isola District!!!",
                "main_img"=> "apartments/23.jpg",
                "max_guests"=> "6",
                "rooms"=> "4",
                "beds"=> "6",
                "baths"=> "2",
                "mq"=> "120",
                "address"=> "via Carlo Farini, 3",
                "latitude"=> "45.48322",
                "longitude"=> "9.18156",
                "price"=> 67.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "2",
                "title"=> "Appartamento viale Monza",
                "description"=> "Luminoso appartamento vicino al Parco Trenno. Il quartiere è un poco lontano dal centro, ma molto caratteristico e collegato con i mezzi pubblici. ",
                "main_img"=> "apartments/24.jpg",
                "max_guests"=> "4",
                "rooms"=> "3",
                "beds"=> "4",
                "baths"=> "2",
                "mq"=> "98",
                "address"=> "viale Monza, 124",
                "latitude"=> "45.50492",
                "longitude"=> "9.22244",
                "price"=> 65.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "3",
                "title"=> "Appartamento Liguria",
                "description"=> "In zona sud, accanto ad un parco, ampio e luminoso loft al piano seminterrato con camera da letto matrimoniale separata.",
                "main_img"=> "apartments/25.jpg",
                "max_guests"=> "7",
                "rooms"=> "6",
                "beds"=> "7",
                "baths"=> "3",
                "mq"=> "150",
                "address"=> "viale Liguria, 231",
                "latitude"=> "45.44402",
                "longitude"=> "9.17155",
                "price"=> 65.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "4",
                "title"=> "Appartamento Crocetta",
                "description"=> "In zona Crocetta nuovissimo appartamento di 48 mq al 2°piano.",
                "main_img"=> "apartments/26.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "48",
                "address"=> "via Orti, 25",
                "latitude"=> "45.45498",
                "longitude"=> "9.19958",
                "price"=> 98.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "5",
                "title"=> "New studio apartment",
                "description"=> "Nuovissimo monolocale appena restaurato, silenzioso, luminoso e completo di tutti i confort .",
                "main_img"=> "apartments/27.jpg",
                "max_guests"=> "2",
                "rooms"=> "1",
                "beds"=> "1",
                "baths"=> "1",
                "mq"=> "34",
                "address"=> "via Abramo Lincoln, 21",
                "latitude"=> "45.46519",
                "longitude"=> "9.2094",
                "price"=> 33.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "6",
                "title"=> "Monolocale rinnovato",
                "description"=> "Monolocale stile newyorkese, recentemente ristrutturato. Posto all’ultimo piano troverai l’appartamento silenzioso e luminoso. All’interno un divano letto garantisce comodità e ampio spazio nella zona giorno.",
                "main_img"=> "apartments/28.jpg",
                "max_guests"=> "1",
                "rooms"=> "1",
                "beds"=> "1",
                "baths"=> "1",
                "mq"=> "25",
                "address"=> "corso Monforte, 9",
                "latitude"=> "45.46714",
                "longitude"=> "9.2019",
                "price"=> 43.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Loft - MM lilla",
                "description"=> "Bellissimo Loft finemente ristrutturato, in elegante palazzo del 1900 situato a Milano, dagli spazi molto ampi e luminosi.",
                "main_img"=> "apartments/29.jpg",
                "max_guests"=> "4",
                "rooms"=> "3",
                "beds"=> "4",
                "baths"=> "2",
                "mq"=> "96",
                "address"=> "viale Fulvio Testi, 22",
                "latitude"=> "45.50421",
                "longitude"=> "9.19984",
                "price"=> 54.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "2",
                "title"=> "Appartamento spazioso",
                "description"=> "Grazie alla posizione centrale di questo alloggio, l'intero gruppo potrà accedere facilmente a tutte le attrazioni locali.",
                "main_img"=> "apartments/30.jpg",
                "max_guests"=> "3",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "63",
                "address"=> "via Rogoredo, 33",
                "latitude"=> "45.42885",
                "longitude"=> "9.24761",
                "price"=> 73.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "3",
                "title"=> "Espinasse vibing house",
                "description"=> "La Metropolitana a 400 metri ti permette di spostarti dove vuoi: in 10' raggiungerai il Duomo e le zone più IN della movida Milanese.",
                "main_img"=> "apartments/31.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "49",
                "address"=> "viale Carlo Espinasse, 137",
                "latitude"=> "45.50172",
                "longitude"=> "9.13785",
                "price"=> 49.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "4",
                "title"=> "Confortevole appartamento",
                "description"=> "Immobile confortevole completamente ristrutturato con letto matrimoniale e divano.",
                "main_img"=> "apartments/32.jpg",
                "max_guests"=> "2",
                "rooms"=> "1",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "46",
                "address"=> "via dei Missaglia, 78",
                "latitude"=> "45.42529",
                "longitude"=> "9.17968",
                "price"=> 37.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "5",
                "title"=> "Splendido appartamento Comasina",
                "description"=> "Splendido appartamento in via Comasina, sito al 4 piano , dotato di ogni confort non dovrai pensare a nulla.",
                "main_img"=> "apartments/33.jpg",
                "max_guests"=> "6",
                "rooms"=> "4",
                "beds"=> "6",
                "baths"=> "3",
                "mq"=> "163",
                "address"=> "via Comasina, 76",
                "latitude"=> "45.52881",
                "longitude"=> "9.16334",
                "price"=> 45.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "6",
                "title"=> "Luminoso appartamento - Morbegno",
                "description"=> "Luminoso appartamento nel quartiere NoLo. Il quartiere è un poco lontano dal centro, ma molto caratteristico e collegato con i mezzi pubblici. ",
                "main_img"=> "apartments/34.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "56",
                "address"=> "piazza Morbegno, 3",
                "latitude"=> "45.49308",
                "longitude"=> "9.21654",
                "price"=> 80.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Loft Red",
                "description"=> "Il LOFT RED è accogliente e a pochi passi dalla metropolitana MM1 per raggiungere in sole 5 fermate il centro di Milano. Lo spazio dispone di un soppalco con letto matrimoniale e un divano letto matrimoniale nell’open space.",
                "main_img"=> "apartments/35.jpg",
                "max_guests"=> "3",
                "rooms"=> "2",
                "beds"=> "3",
                "baths"=> "1",
                "mq"=> "65",
                "address"=> "piazzale Siena, 11",
                "latitude"=> "45.46447",
                "longitude"=> "9.13726",
                "price"=> 78.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "2",
                "title"=> "Bilocale lussuoso",
                "description"=> "Nuovo bilocale Lussuoso adatto per viaggiatori da tutto il mondo.",
                "main_img"=> "apartments/36.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "46",
                "address"=> "via Luigi Pulci, 19",
                "latitude"=> "45.51448",
                "longitude"=> "9.20761",
                "price"=> 56.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "3",
                "title"=> "Nuovo appartamento",
                "description"=> "Nuovo appartamento in via D'Adda, di fronte a Cross Studio, ben collegato con il centro, supermercato, banca, ristoranti, bar e fermata dell'autobus in fondo alla casa, parcheggio gratuito in strada.",
                "main_img"=> "apartments/37.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "56",
                "address"=> "via D\Adda, 12",
                "latitude"=> "45.48004",
                "longitude"=> "9.05472",
                "price"=> 32.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "4",
                "title"=> "Appartamento ristrutturato - Mazzini",
                "description"=> "Finemente ristrutturato in via Giuseppe Mazzini, al primo piano.",
                "main_img"=> "apartments/38.jpg",
                "max_guests"=> "4",
                "rooms"=> "3",
                "beds"=> "4",
                "baths"=> "2",
                "mq"=> "98",
                "address"=> "via Giuseppe Mazzini, 32",
                "latitude"=> "45.43379",
                "longitude"=> "9.11706",
                "price"=> 38.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "5",
                "title"=> "Attico cozy",
                "description"=> "Quiet attic room, equipped with a desk for working, in small villa in a central area",
                "main_img"=> "apartments/39.jpg",
                "max_guests"=> "1",
                "rooms"=> "1",
                "beds"=> "1",
                "baths"=> "1",
                "mq"=> "25",
                "address"=> "Via Wolfgang Amadeus Mozart, 54",
                "latitude"=> "45.53842",
                "longitude"=> "9.2855",
                "price"=> 67.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Loft Navigli",
                "description"=> "Se desiderate stare in un loft moderno nel cuore antico di Milano cioè i Navigli , dove c’è la metro praticamente sotto casa e a meno di 10 minuti di passeggiata arrivate ai Navigli ,Quartiere frizzante che si snoda tra negozi vintage.",
                "main_img"=> "apartments/40.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "45",
                "address"=> "Alzaia Naviglio Gransde, 3",
                "latitude"=> "45.45119",
                "longitude"=> "9.17166",
                "price"=> 65.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "2",
                "title"=> "Alloggio Porta Vittoria",
                "description"=> "Grazie alla posizione centrale di questo alloggio, l'intero gruppo potrà accedere facilmente a tutte le attrazioni locali. Posizione strategica a 10 min dal duomo a piedi e vicino Linate . Presenti tutte le attività di prima necessità.",
                "main_img"=> "apartments/41.jpg",
                "max_guests"=> "4",
                "rooms"=> "2",
                "beds"=> "3",
                "baths"=> "1",
                "mq"=> "56",
                "address"=> "Corso di Porta Romana, 12",
                "latitude"=> "45.46238",
                "longitude"=> "9.20188",
                "price"=> 72.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "3",
                "title"=> "Alloggio Moscova",
                "description"=> "Questo splendido luminoso (e silenzioso)  Loft, recentemente ristrutturato è situato nel cuore di Moscova, una della più rinomate zone residenziali di Milano. L'ingresso avviene tramite self-check-in, pertanto potrete arrivare a qualsiasi orario.",
                "main_img"=> "apartments/42.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "1",
                "baths"=> "1",
                "mq"=> "37",
                "address"=> "via San Marco, 34",
                "latitude"=> "45.47789",
                "longitude"=> "9.18899",
                "price"=> 98.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "4",
                "title"=> "Bicocca Monolocale",
                "description"=> "L'appartamento è in un complesso nuovo con due  linee di metropolitana a pochi minuti  e un autobus (87) sotto casa da e per per la stazione centrale.",
                "main_img"=> "apartments/43.jpg",
                "max_guests"=> "1",
                "rooms"=> "1",
                "beds"=> "1",
                "baths"=> "1",
                "mq"=> "25",
                "address"=> "viale Sarca, 202",
                "latitude"=> "45.5181",
                "longitude"=> "9.2099",
                "price"=> 120.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "5",
                "title"=> "Crescenzago Suite",
                "description"=> "Spazio confortevole e rilassante, adatto a coppie, famiglie o professionisti. Supermarket/Farmacia/Pasticceria/Pizzerie e Ristoranti tipici entro 100m Fermata del bus sotto casa e Metro Linea Verde “Crescenzago” a 300m. 20’ dalla Stazione Centrale, 20’ da Duomo.",
                "main_img"=> "apartments/44.jpg",
                "max_guests"=> "3",
                "rooms"=> "2",
                "beds"=> "3",
                "baths"=> "1",
                "mq"=> "88",
                "address"=> "via Palmanova, 137",
                "latitude"=> "45.50693",
                "longitude"=> "9.24959",
                "price"=> 87.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "6",
                "title"=> "Portello Suite",
                "description"=> "Ci troviamo a 100 metri dall'entrata del Centro Congressi MiCO, 50 metri dall'entrata di Fiera Milano città.",
                "main_img"=> "apartments/45.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "51",
                "address"=> "piazzale Portello, 3",
                "latitude"=> "45.49037",
                "longitude"=> "9.14589",
                "price"=> 92.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "1",
                "title"=> "Tre Torri Suite",
                "description"=> "Il nostro appartamento è un seminterrato di 70mq appena ristrutturato ed arredato con tutti i comfort necessari per il vostro soggiorno in famiglia o per lavoro, nel cuore di Milano.",
                "main_img"=> "apartments/46.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "70",
                "address"=> "piazza Tre Torri, 20",
                "latitude"=> "45.4777",
                "longitude"=> "9.15618",
                "price"=> 81.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "2",
                "title"=> "Appartamento colorato - MM2 Centrale",
                "description"=> "I colori centrali sono un appartamento di 100 m ² in un elegante edificio in stile Liberty a soli 3 minuti dalla stazione centrale.",
                "main_img"=> "apartments/47.jpg",
                "max_guests"=> "3",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "76",
                "address"=> "via Venini, 18",
                "latitude"=> "45.48935",
                "longitude"=> "9.21405",
                "price"=> 110.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "3",
                "title"=> "Bright House",
                "description"=> "Questo grazioso bilocale vicino al Duomo di Milano è provvisto di una spaziosa zona living con un letto matrimoniale a scomparsa e un divano letto singolo.",
                "main_img"=> "apartments/48.jpg",
                "max_guests"=> "2",
                "rooms"=> "2",
                "beds"=> "2",
                "baths"=> "1",
                "mq"=> "77",
                "address"=> "via Gesù, 17",
                "latitude"=> "45.47012",
                "longitude"=> "9.19623",
                "price"=> 123.00,
                "visible"=> "1",
            ],
            [
                "user_id"=> "6",
                "title"=> "Bilocale Affori",
                "description"=> "Soggiornare a Milano, sentendosi a casa, questa è la mia Filosofia! Questo ampio bilocale, completamente e finemente ristrutturato con materiali ricercati ed elementi di design a fine marzo 2023, offre la soluzione ideale per chi non vuole pernottare nella caotica e rumorosa Milano.",
                "main_img"=> "apartments/49.jpg",
                "max_guests"=> "3",
                "rooms"=> "2",
                "beds"=> "3",
                "baths"=> "1",
                "mq"=> "61",
                "address"=> "via Pellegrino Rossi, 45",
                "latitude"=> "45.51066",
                "longitude"=> "9.17572",
                "price"=> 89.00,
                "visible"=> "1",
            ],
        ];

        foreach ($apartments as $key => $apartment) {
            Apartment::create([
                'user_id' => $apartment['user_id'],
                'title' => $apartment['title'],
                'slug' => Str::slug($apartment['title']),
                'description' => $apartment['description'],
                'main_img' => $apartment['main_img'],
                'max_guests' => $apartment['max_guests'],
                'rooms' => $apartment['rooms'],
                'beds' => $apartment['beds'],
                'baths' => $apartment['baths'],
                'mq' => $apartment['mq'],
                'address' => $apartment['address'],
                'latitude' => $apartment['latitude'],
                'longitude' => $apartment['longitude'],
                'price' => $apartment['price'],
                'visible' => $apartment['visible'],

             ]);
        }

    }
}
